<?php

    // SETUP ERROR MESSAGES

    // User class
    $this->error_message["1"  ] = "Username is invalid.";
    $this->error_message["2"  ] = "Last name is undefined.";
    $this->error_message["3"  ] = "First name is undefined.";
    $this->error_message["4"  ] = "Active flag is invalid.";
    $this->error_message["5"  ] = "Email address is invalid.";
    $this->error_message["6"  ] = "Class flag is invalid.";
    $this->error_message["7"  ] = "Password is invalid.";
    $this->error_message["8"  ] = "Email address 2 is invalid.";
    $this->error_message["9"  ] = "State is invalid.";
    $this->error_message["10"  ] = "Customer is invalid.";
    $this->error_message["11"  ] = "Wholesaler is invalid.";
    $this->error_message["12"  ] = "Customer does not exist.";
    $this->error_message["13"  ] = "Wholesaler does not exist.";

        // Chat Class
    $this->error_message["51" ] = "Chat who is not identified.";
    
    // Document
    $this->error_message["60" ] = "Document ID is invalid.";
    $this->error_message["61" ] = "Filename is invalid.";
    $this->error_message["62" ] = "Document type is invalid.";
    $this->error_message["63" ] = "Frontpage flag is invalid.";

        // Wholesaler Class
    $this->error_message["100"] = "Wholesaler ID is invalid.";
    $this->error_message["101"] = "Company is invalid.";

        // Audit Class
    $this->error_message["110"] = "Object is invalid.";
    $this->error_message["111"] = "ID is invalid.";
    $this->error_message["112"] = "Activity is invalid.";

        //Customer Class
    $this->error_message["120"] = "Type is invalid.";
    $this->error_message["121"] = "Postal Same value is invalid.";
    $this->error_message["122"] = "Postal Code is invalid.";
    $this->error_message["123"] = "Mobile Number is invalid.";
    $this->error_message["124"] = "Phone Number is invalid.";
    $this->error_message["125"] = "Fax Number is invalid.";
    $this->error_message["126"] = "ABN is invalid.";
    $this->error_message["127"] = "Birthdate is invalid.";

        //Service Types Class
    $this->error_message["130"] = "Service Type is empty.";
    $this->error_message["131"] = "Description is empty.";

        //Wholesaler Service Types Class
    $this->error_message["140"] = "Type ID is invalid.";
    $this->error_message["141"] = "Service Type is invalid.";

        //Service Class
    $this->error_message["150"] = "State is invalid.";
    $this->error_message["151"] = "Start Date is invalid.";
    $this->error_message["152"] = "Wholesaler Plan is invalid.";
    $this->error_message["153"] = "Retrail Plan is invalid.";
    $this->error_message["154"] = "Contract Date is invalid.";
    $this->error_message["155"] = "Finish Date is invalid.";

        //Service Attributes Class
    $this->error_message["160"] = "Service ID is invalid.";
    $this->error_message["161"] = "Parameter is invalid.";
    $this->error_message["162"] = "Value is invalid.";

        //Plans Class
    $this->error_message["170"] = "Description is invalid.";
    $this->error_message["171"] = "Parent Plan ID is invalid.";
    $this->error_message["172"] = "Sub Type is invalid.";

        //Orders Class
    $this->error_message["180"] = "Start Date is invalid.";
    $this->error_message["181"] = "Finish Date is invalid.";

        //Plan Extras
    $this->error_message["190"] = "Extra ID is invalid.";
    $this->error_message["191"] = "Plan ID is invalid.";
    $this->error_message["192"] = "Type in Extras is invalid.";

        //Authorised Rep Class
    $this->error_message["200"] = "Authorised Representative's First Name is invalid.";
    $this->error_message["201"] = "Authorised Representative's Surname is invalid.";
    $this->error_message["202"] = "Authorised Representative's Birthdate is invalid.";
    $this->error_message["204"] = "Authorised Representative's Primary ID is invalid.";
    $this->error_message["205"] = "Authorised Representative's Primary ID Number is invalid.";
    $this->error_message["206"] = "Points must be 100 or more.";
    $this->error_message["207"] = "Contact Number is invalid.";

        //Secondary Ids Class
    $this->error_message["210"] = "Authorised Representative's Secondary ID is invalid.";
    $this->error_message["211"] = "Authorised Representative's Secondary ID Number is invalid.";

        //Realms Class
    $this->error_message["220"] = "Realm invalid.";

        //Postcode Class
    $this->error_message["230"] = "Locality invalid.";
    $this->error_message["231"] = "State invalid.";

        //Orders States Class
    $this->error_message["240"] = "Order ID invalid.";
    $this->error_message["241"] = "State Name invalid.";

        //Outbound Voice FNN
    $this->error_message["250"] = "FNN invalid.";
    $this->error_message["251"] = "Start date invalid.";
    $this->error_message["252"] = "Stop date invalid.";

        //Service Billing Once Off
    $this->error_message["260"] = "Main Unit Amount Invalid.";
    $this->error_message["261"] = "Wholesale Unit Amount Invalid.";
    $this->error_message["262"] = "Quantity Invalid.";
    $this->error_message["263"] = "Item Type Invalid.";

        //Service Billing Invoices Items
    $this->error_message["270"] = "Invoice ID Invalid.";
    $this->error_message["271"] = "Unit Amount Invalid.";
    $this->error_message["272"] = "Line Type Invalid.";

        //Plan Groups
    $this->error_message["280"] = "Group ID does not exist.";
    $this->error_message["281"] = "Group ID is invalid.";

        //Calls Cost
    $this->error_message["290"] = "Internation Rate ID is invalid.";
    $this->error_message["291"] = "Country is invalid.";