drop table telstra_utr;

CREATE TABLE `telstra_utr` (
  `seq` varchar(15) NOT NULL,
WholesaleRedirectionGroup varchar(6) not null,
ProductBillingIdentifier varchar(8) not null,
BillingElementCode varchar(8) not null,
ActivityCompletedIndicator char(1) not null,
ServChargeItemGrp varchar(20) not null,
UnbilledIndicator char(1) not null,
GSTPercentageRate float(7,4) not null,
RateStructureStartDate date not null,
RateStructureEndDate date not null,
Description varchar(80) not null,
UOMCode varchar(5) not null,
RatePeriod char(1) not null,
RatePeriodDescription varchar(10) not null,
Flagfallamountsignindicator char(1) not null,
FlagfallAmount float(15,7) not null,
UnitRate float(15,7) not null,
PulseInterval float(7,3) not null,
DayOfWeekStart char(1) not null,
DayOfWeekEnd char(1) not null,
CallRangeStartTime time not null,
CallRangeEndTime time not null,
DistanceRangeCode  varchar(4) not null,
DistanceRangeDescription varchar(50) not null,
UnitrateMethod char(1) not null,
UnitHighQTY BIGINT unsigned not null,
UnitLowQTY BIGINT unsigned not null,
MaxChargeamount float(11,4) not null,
MinChargeamount float(11,4) not null,
MaxCallLength BIGINT unsigned not null,
MinCalllength BIGINT unsigned not null,
RateQTYdependIndicator char(1) not null,
TariffChangeIndicator char(1) not null,
  KEY `seq` (`seq`)
);